// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTagParams creates a new DeleteTagParams object
//
// There are no default values defined in the spec.
func NewDeleteTagParams() DeleteTagParams {
	_ = "STUB: not implemented"
	return *

	// DeleteTagParams contains all the bound params for the delete tag operation
	// typically these are obtained from a http.Request
	//
	// swagger:parameters deleteTag
	new(DeleteTagParams)
}

type DeleteTagParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the tag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	TagID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteTagParams() beforehand.
func (o *DeleteTagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindFlagID binds and validates parameter FlagID from path.
func (o *DeleteTagParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *DeleteTagParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindTagID binds and validates parameter TagID from path.
func (o *DeleteTagParams) bindTagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateTagID carries out validations for parameter TagID
func (o *DeleteTagParams) validateTagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
