// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteTagHandlerFunc turns a function with the right signature into a delete tag handler
type DeleteTagHandlerFunc func(DeleteTagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTagHandlerFunc) Handle(params DeleteTagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteTagHandler interface for that can handle valid delete tag params
	return *new(middleware.Responder)
}

type DeleteTagHandler interface {
	Handle(DeleteTagParams) middleware.Responder
}

// NewDeleteTag creates a new http.Handler for the delete tag operation
func NewDeleteTag(ctx *middleware.Context, handler DeleteTagHandler) *DeleteTag {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteTag swagger:route DELETE /flags/{flagID}/tags/{tagID} tag deleteTag

DeleteTag delete tag API
*/
type DeleteTag struct {
	Context *middleware.Context
	Handler DeleteTagHandler
}

func (o *DeleteTag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
