// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeleteTagOKCode is the HTTP code returned for type DeleteTagOK
const DeleteTagOKCode int = 200

/*
DeleteTagOK deleted

swagger:response deleteTagOK
*/
type DeleteTagOK struct {
}

// NewDeleteTagOK creates DeleteTagOK with default headers values
func NewDeleteTagOK() *DeleteTagOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *DeleteTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
DeleteTagDefault generic error response

swagger:response deleteTagDefault
*/
type DeleteTagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTagDefault creates DeleteTagDefault with default headers values
func NewDeleteTagDefault(code int) *DeleteTagDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the delete tag default response
func (o *DeleteTagDefault) WithStatusCode(code int) *DeleteTagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the delete tag default response
func (o *DeleteTagDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the delete tag default response
func (o *DeleteTagDefault) WithPayload(payload *models.Error) *DeleteTagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the delete tag default response
func (o *DeleteTagDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *DeleteTagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
