// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewFindAllTagsParams creates a new FindAllTagsParams object
//
// There are no default values defined in the spec.
func NewFindAllTagsParams() FindAllTagsParams {
	_ = "STUB: not implemented"
	return *new(FindAllTagsParams)
}

// FindAllTagsParams contains all the bound params for the find all tags operation
// typically these are obtained from a http.Request
//
// swagger:parameters findAllTags
type FindAllTagsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the numbers of tags to return
	  In: query
	*/
	Limit *int64

	/*return tags given the offset, it should usually set together with limit
	  In: query
	*/
	Offset *int64

	/*return tags partially matching given value
	  In: query
	*/
	ValueLike *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFindAllTagsParams() beforehand.
func (o *FindAllTagsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *FindAllTagsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindOffset binds and validates parameter Offset from query.
func (o *FindAllTagsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindValueLike binds and validates parameter ValueLike from query.
func (o *FindAllTagsParams) bindValueLike(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations
