// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindTagsHandlerFunc turns a function with the right signature into a find tags handler
type FindTagsHandlerFunc func(FindTagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindTagsHandlerFunc) Handle(params FindTagsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// FindTagsHandler interface for that can handle valid find tags params
	return *new(middleware.Responder)
}

type FindTagsHandler interface {
	Handle(FindTagsParams) middleware.Responder
}

// NewFindTags creates a new http.Handler for the find tags operation
func NewFindTags(ctx *middleware.Context, handler FindTagsHandler) *FindTags {
	_ = "STUB: not implemented"
	return nil
}

/*
	FindTags swagger:route GET /flags/{flagID}/tags tag findTags

FindTags find tags API
*/
type FindTags struct {
	Context *middleware.Context
	Handler FindTagsHandler
}

func (o *FindTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
