// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindTagsOKCode is the HTTP code returned for type FindTagsOK
const FindTagsOKCode int = 200

/*
FindTagsOK tag ordered by tagID

swagger:response findTagsOK
*/
type FindTagsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tag `json:"body,omitempty"`
}

// NewFindTagsOK creates FindTagsOK with default headers values
func NewFindTagsOK() *FindTagsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find tags o k response
func (o *FindTagsOK) WithPayload(payload []*models.Tag) *FindTagsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find tags o k response
func (o *FindTagsOK) SetPayload(payload []*models.Tag) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindTagsDefault generic error response

swagger:response findTagsDefault
*/
type FindTagsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindTagsDefault creates FindTagsDefault with default headers values
func NewFindTagsDefault(code int) *FindTagsDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the find tags default response
func (o *FindTagsDefault) WithStatusCode(code int) *FindTagsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find tags default response
func (o *FindTagsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find tags default response
func (o *FindTagsDefault) WithPayload(payload *models.Error) *FindTagsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find tags default response
func (o *FindTagsDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindTagsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
