// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateVariantHandlerFunc turns a function with the right signature into a create variant handler
type CreateVariantHandlerFunc func(CreateVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateVariantHandlerFunc) Handle(params CreateVariantParams) middleware.Responder {
	_ = "STUB: not implemented"

	// CreateVariantHandler interface for that can handle valid create variant params
	return *new(middleware.Responder)
}

type CreateVariantHandler interface {
	Handle(CreateVariantParams) middleware.Responder
}

// NewCreateVariant creates a new http.Handler for the create variant operation
func NewCreateVariant(ctx *middleware.Context, handler CreateVariantHandler) *CreateVariant {
	_ = "STUB: not implemented"
	return nil
}

/*
	CreateVariant swagger:route POST /flags/{flagID}/variants variant createVariant

CreateVariant create variant API
*/
type CreateVariant struct {
	Context *middleware.Context
	Handler CreateVariantHandler
}

func (o *CreateVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
