// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewCreateVariantParams creates a new CreateVariantParams object
//
// There are no default values defined in the spec.
func NewCreateVariantParams() CreateVariantParams {
	_ = "STUB: not implemented"
	return *new(CreateVariantParams)
}

// CreateVariantParams contains all the bound params for the create variant operation
// typically these are obtained from a http.Request
//
// swagger:parameters createVariant
type CreateVariantParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*create a variant
	  Required: true
	  In: body
	*/
	Body *models.CreateVariantRequest

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateVariantParams() beforehand.
func (o *CreateVariantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object

// bindFlagID binds and validates parameter FlagID from path.
func (o *CreateVariantParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *CreateVariantParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
