// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteVariantHandlerFunc turns a function with the right signature into a delete variant handler
type DeleteVariantHandlerFunc func(DeleteVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteVariantHandlerFunc) Handle(params DeleteVariantParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteVariantHandler interface for that can handle valid delete variant params
	return *new(middleware.Responder)
}

type DeleteVariantHandler interface {
	Handle(DeleteVariantParams) middleware.Responder
}

// NewDeleteVariant creates a new http.Handler for the delete variant operation
func NewDeleteVariant(ctx *middleware.Context, handler DeleteVariantHandler) *DeleteVariant {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteVariant swagger:route DELETE /flags/{flagID}/variants/{variantID} variant deleteVariant

DeleteVariant delete variant API
*/
type DeleteVariant struct {
	Context *middleware.Context
	Handler DeleteVariantHandler
}

func (o *DeleteVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
