// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteVariantParams creates a new DeleteVariantParams object
//
// There are no default values defined in the spec.
func NewDeleteVariantParams() DeleteVariantParams {
	_ = "STUB: not implemented"
	return *new(DeleteVariantParams)
}

// DeleteVariantParams contains all the bound params for the delete variant operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteVariant
type DeleteVariantParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the variant
	  Required: true
	  Minimum: 1
	  In: path
	*/
	VariantID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteVariantParams() beforehand.
func (o *DeleteVariantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindFlagID binds and validates parameter FlagID from path.
func (o *DeleteVariantParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *DeleteVariantParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindVariantID binds and validates parameter VariantID from path.
func (o *DeleteVariantParams) bindVariantID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateVariantID carries out validations for parameter VariantID
func (o *DeleteVariantParams) validateVariantID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
