// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeleteVariantOKCode is the HTTP code returned for type DeleteVariantOK
const DeleteVariantOKCode int = 200

/*
DeleteVariantOK deleted

swagger:response deleteVariantOK
*/
type DeleteVariantOK struct {
}

// NewDeleteVariantOK creates DeleteVariantOK with default headers values
func NewDeleteVariantOK() *DeleteVariantOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *DeleteVariantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
DeleteVariantDefault generic error response

swagger:response deleteVariantDefault
*/
type DeleteVariantDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteVariantDefault creates DeleteVariantDefault with default headers values
func NewDeleteVariantDefault(code int) *DeleteVariantDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the delete variant default response
func (o *DeleteVariantDefault) WithStatusCode(code int) *DeleteVariantDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the delete variant default response
func (o *DeleteVariantDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the delete variant default response
func (o *DeleteVariantDefault) WithPayload(payload *models.Error) *DeleteVariantDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the delete variant default response
func (o *DeleteVariantDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *DeleteVariantDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
