// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindVariantsHandlerFunc turns a function with the right signature into a find variants handler
type FindVariantsHandlerFunc func(FindVariantsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindVariantsHandlerFunc) Handle(params FindVariantsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// FindVariantsHandler interface for that can handle valid find variants params
	return *new(middleware.Responder)
}

type FindVariantsHandler interface {
	Handle(FindVariantsParams) middleware.Responder
}

// NewFindVariants creates a new http.Handler for the find variants operation
func NewFindVariants(ctx *middleware.Context, handler FindVariantsHandler) *FindVariants {
	_ = "STUB: not implemented"
	return nil
}

/*
	FindVariants swagger:route GET /flags/{flagID}/variants variant findVariants

FindVariants find variants API
*/
type FindVariants struct {
	Context *middleware.Context
	Handler FindVariantsHandler
}

func (o *FindVariants) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
