// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindVariantsOKCode is the HTTP code returned for type FindVariantsOK
const FindVariantsOKCode int = 200

/*
FindVariantsOK variant ordered by variantID

swagger:response findVariantsOK
*/
type FindVariantsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Variant `json:"body,omitempty"`
}

// NewFindVariantsOK creates FindVariantsOK with default headers values
func NewFindVariantsOK() *FindVariantsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find variants o k response
func (o *FindVariantsOK) WithPayload(payload []*models.Variant) *FindVariantsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find variants o k response
func (o *FindVariantsOK) SetPayload(payload []*models.Variant) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindVariantsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindVariantsDefault generic error response

swagger:response findVariantsDefault
*/
type FindVariantsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindVariantsDefault creates FindVariantsDefault with default headers values
func NewFindVariantsDefault(code int) *FindVariantsDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the find variants default response
func (o *FindVariantsDefault) WithStatusCode(code int) *FindVariantsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find variants default response
func (o *FindVariantsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find variants default response
func (o *FindVariantsDefault) WithPayload(payload *models.Error) *FindVariantsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find variants default response
func (o *FindVariantsDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindVariantsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
