// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewPutVariantParams creates a new PutVariantParams object
//
// There are no default values defined in the spec.
func NewPutVariantParams() PutVariantParams {
	_ = "STUB: not implemented"
	return *new(PutVariantParams)
}

// PutVariantParams contains all the bound params for the put variant operation
// typically these are obtained from a http.Request
//
// swagger:parameters putVariant
type PutVariantParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*update a variant
	  Required: true
	  In: body
	*/
	Body *models.PutVariantRequest

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the variant
	  Required: true
	  Minimum: 1
	  In: path
	*/
	VariantID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutVariantParams() beforehand.
func (o *PutVariantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object

// bindFlagID binds and validates parameter FlagID from path.
func (o *PutVariantParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *PutVariantParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindVariantID binds and validates parameter VariantID from path.
func (o *PutVariantParams) bindVariantID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateVariantID carries out validations for parameter VariantID
func (o *PutVariantParams) validateVariantID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
