// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutVariantOKCode is the HTTP code returned for type PutVariantOK
const PutVariantOKCode int = 200

/*
PutVariantOK variant just updated

swagger:response putVariantOK
*/
type PutVariantOK struct {

	/*
	  In: Body
	*/
	Payload *models.Variant `json:"body,omitempty"`
}

// NewPutVariantOK creates PutVariantOK with default headers values
func NewPutVariantOK() *PutVariantOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the put variant o k response
func (o *PutVariantOK) WithPayload(payload *models.Variant) *PutVariantOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put variant o k response
func (o *PutVariantOK) SetPayload(payload *models.Variant) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutVariantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
PutVariantDefault generic error response

swagger:response putVariantDefault
*/
type PutVariantDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutVariantDefault creates PutVariantDefault with default headers values
func NewPutVariantDefault(code int) *PutVariantDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the put variant default response
func (o *PutVariantDefault) WithStatusCode(code int) *PutVariantDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put variant default response
func (o *PutVariantDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put variant default response
func (o *PutVariantDefault) WithPayload(payload *models.Error) *PutVariantDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put variant default response
func (o *PutVariantDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutVariantDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
