// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/url"
)

// PutVariantURL generates an URL for the put variant operation
type PutVariantURL struct {
	FlagID    int64
	VariantID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutVariantURL) WithBasePath(bp string) *PutVariantURL {
	_ = "STUB: not implemented"
	return nil
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutVariantURL) SetBasePath(bp string) {
	_ = "STUB: not implemented"

	// Build a url path and query string
	return
}

func (o *PutVariantURL) Build() (*url.URL, error) { _ = "STUB: not implemented"; return nil, nil }

// Must is a helper function to panic when the url builder returns an error
func (o *PutVariantURL) Must(u *url.URL, err error) *url.URL { _ = "STUB: not implemented"; return nil }

// String returns the string representation of the path with query string
func (o *PutVariantURL) String() string { _ = "STUB: not implemented"; return "" }

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutVariantURL) BuildFull(scheme, host string) (*url.URL, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StringFull returns the string representation of a complete url
func (o *PutVariantURL) StringFull(scheme, host string) string {
	_ = "STUB: not implemented"
	return ""
}
