// Code generated by go-swagger; DO NOT EDIT.

package variant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutVariantHandlerFunc turns a function with the right signature into a put variant handler
type PutVariantHandlerFunc func(PutVariantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutVariantHandlerFunc) Handle(params PutVariantParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutVariantHandler interface for that can handle valid put variant params
	return *new(middleware.Responder)
}

type PutVariantHandler interface {
	Handle(PutVariantParams) middleware.Responder
}

// NewPutVariant creates a new http.Handler for the put variant operation
func NewPutVariant(ctx *middleware.Context, handler PutVariantHandler) *PutVariant {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutVariant swagger:route PUT /flags/{flagID}/variants/{variantID} variant putVariant

PutVariant put variant API
*/
type PutVariant struct {
	Context *middleware.Context
	Handler PutVariantHandler
}

func (o *PutVariant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
