// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindDistributionsOKCode is the HTTP code returned for type FindDistributionsOK
const FindDistributionsOKCode int = 200

/*
FindDistributionsOK distribution under the segment

swagger:response findDistributionsOK
*/
type FindDistributionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Distribution `json:"body,omitempty"`
}

// NewFindDistributionsOK creates FindDistributionsOK with default headers values
func NewFindDistributionsOK() *FindDistributionsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find distributions o k response
func (o *FindDistributionsOK) WithPayload(payload []*models.Distribution) *FindDistributionsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find distributions o k response
func (o *FindDistributionsOK) SetPayload(payload []*models.Distribution) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *FindDistributionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindDistributionsDefault generic error response

swagger:response findDistributionsDefault
*/
type FindDistributionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindDistributionsDefault creates FindDistributionsDefault with default headers values
func NewFindDistributionsDefault(code int) *FindDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the find distributions default response
func (o *FindDistributionsDefault) WithStatusCode(code int) *FindDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find distributions default response
func (o *FindDistributionsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find distributions default response
func (o *FindDistributionsDefault) WithPayload(payload *models.Error) *FindDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find distributions default response
func (o *FindDistributionsDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *FindDistributionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
