// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutDistributionsOKCode is the HTTP code returned for type PutDistributionsOK
const PutDistributionsOKCode int = 200

/*
PutDistributionsOK distribution under the segment

swagger:response putDistributionsOK
*/
type PutDistributionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Distribution `json:"body,omitempty"`
}

// NewPutDistributionsOK creates PutDistributionsOK with default headers values
func NewPutDistributionsOK() *PutDistributionsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the put distributions o k response
func (o *PutDistributionsOK) WithPayload(payload []*models.Distribution) *PutDistributionsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put distributions o k response
func (o *PutDistributionsOK) SetPayload(payload []*models.Distribution) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *PutDistributionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
PutDistributionsDefault generic error response

swagger:response putDistributionsDefault
*/
type PutDistributionsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutDistributionsDefault creates PutDistributionsDefault with default headers values
func NewPutDistributionsDefault(code int) *PutDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the put distributions default response
func (o *PutDistributionsDefault) WithStatusCode(code int) *PutDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put distributions default response
func (o *PutDistributionsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put distributions default response
func (o *PutDistributionsDefault) WithPayload(payload *models.Error) *PutDistributionsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put distributions default response
func (o *PutDistributionsDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *PutDistributionsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
