// Code generated by go-swagger; DO NOT EDIT.

package distribution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutDistributionsHandlerFunc turns a function with the right signature into a put distributions handler
type PutDistributionsHandlerFunc func(PutDistributionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutDistributionsHandlerFunc) Handle(params PutDistributionsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutDistributionsHandler interface for that can handle valid put distributions params
	return *new(middleware.Responder)
}

type PutDistributionsHandler interface {
	Handle(PutDistributionsParams) middleware.Responder
}

// NewPutDistributions creates a new http.Handler for the put distributions operation
func NewPutDistributions(ctx *middleware.Context, handler PutDistributionsHandler) *PutDistributions {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutDistributions swagger:route PUT /flags/{flagID}/segments/{segmentID}/distributions distribution putDistributions

replace the distribution with the new setting
*/
type PutDistributions struct {
	Context *middleware.Context
	Handler PutDistributionsHandler
}

func (o *PutDistributions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
