// Code generated by go-swagger; DO NOT EDIT.

package export

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetExportSqliteOKCode is the HTTP code returned for type GetExportSqliteOK
const GetExportSqliteOKCode int = 200

/*
GetExportSqliteOK OK

swagger:response getExportSqliteOK
*/
type GetExportSqliteOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetExportSqliteOK creates GetExportSqliteOK with default headers values
func NewGetExportSqliteOK() *GetExportSqliteOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the get export sqlite o k response
func (o *GetExportSqliteOK) WithPayload(payload io.ReadCloser) *GetExportSqliteOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get export sqlite o k response
func (o *GetExportSqliteOK) SetPayload(payload io.ReadCloser) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *GetExportSqliteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
GetExportSqliteDefault generic error response

swagger:response getExportSqliteDefault
*/
type GetExportSqliteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetExportSqliteDefault creates GetExportSqliteDefault with default headers values
func NewGetExportSqliteDefault(code int) *GetExportSqliteDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the get export sqlite default response
func (o *GetExportSqliteDefault) WithStatusCode(code int) *GetExportSqliteDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the get export sqlite default response
func (o *GetExportSqliteDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the get export sqlite default response
func (o *GetExportSqliteDefault) WithPayload(payload *models.Error) *GetExportSqliteDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get export sqlite default response
func (o *GetExportSqliteDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetExportSqliteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
