// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openflagr/flagr/swagger_gen/restapi/operations/constraint"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/distribution"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/evaluation"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/export"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/flag"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/health"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/segment"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/tag"
	"github.com/openflagr/flagr/swagger_gen/restapi/operations/variant"
)

// NewFlagrAPI creates a new Flagr instance
func NewFlagrAPI(spec *loads.Document) *FlagrAPI { _ = "STUB: not implemented"; return nil }

/*FlagrAPI Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is "/api/v1".
 */
type FlagrAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// BinProducer registers a producer for the following mime types:
	//   - application/octet-stream
	BinProducer runtime.Producer
	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ConstraintCreateConstraintHandler sets the operation handler for the create constraint operation
	ConstraintCreateConstraintHandler constraint.CreateConstraintHandler
	// FlagCreateFlagHandler sets the operation handler for the create flag operation
	FlagCreateFlagHandler flag.CreateFlagHandler
	// SegmentCreateSegmentHandler sets the operation handler for the create segment operation
	SegmentCreateSegmentHandler segment.CreateSegmentHandler
	// TagCreateTagHandler sets the operation handler for the create tag operation
	TagCreateTagHandler tag.CreateTagHandler
	// VariantCreateVariantHandler sets the operation handler for the create variant operation
	VariantCreateVariantHandler variant.CreateVariantHandler
	// ConstraintDeleteConstraintHandler sets the operation handler for the delete constraint operation
	ConstraintDeleteConstraintHandler constraint.DeleteConstraintHandler
	// FlagDeleteFlagHandler sets the operation handler for the delete flag operation
	FlagDeleteFlagHandler flag.DeleteFlagHandler
	// SegmentDeleteSegmentHandler sets the operation handler for the delete segment operation
	SegmentDeleteSegmentHandler segment.DeleteSegmentHandler
	// TagDeleteTagHandler sets the operation handler for the delete tag operation
	TagDeleteTagHandler tag.DeleteTagHandler
	// VariantDeleteVariantHandler sets the operation handler for the delete variant operation
	VariantDeleteVariantHandler variant.DeleteVariantHandler
	// TagFindAllTagsHandler sets the operation handler for the find all tags operation
	TagFindAllTagsHandler tag.FindAllTagsHandler
	// ConstraintFindConstraintsHandler sets the operation handler for the find constraints operation
	ConstraintFindConstraintsHandler constraint.FindConstraintsHandler
	// DistributionFindDistributionsHandler sets the operation handler for the find distributions operation
	DistributionFindDistributionsHandler distribution.FindDistributionsHandler
	// FlagFindFlagsHandler sets the operation handler for the find flags operation
	FlagFindFlagsHandler flag.FindFlagsHandler
	// SegmentFindSegmentsHandler sets the operation handler for the find segments operation
	SegmentFindSegmentsHandler segment.FindSegmentsHandler
	// TagFindTagsHandler sets the operation handler for the find tags operation
	TagFindTagsHandler tag.FindTagsHandler
	// VariantFindVariantsHandler sets the operation handler for the find variants operation
	VariantFindVariantsHandler variant.FindVariantsHandler
	// ExportGetExportEvalCacheJSONHandler sets the operation handler for the get export eval cache JSON operation
	ExportGetExportEvalCacheJSONHandler export.GetExportEvalCacheJSONHandler
	// ExportGetExportSqliteHandler sets the operation handler for the get export sqlite operation
	ExportGetExportSqliteHandler export.GetExportSqliteHandler
	// FlagGetFlagHandler sets the operation handler for the get flag operation
	FlagGetFlagHandler flag.GetFlagHandler
	// FlagGetFlagEntityTypesHandler sets the operation handler for the get flag entity types operation
	FlagGetFlagEntityTypesHandler flag.GetFlagEntityTypesHandler
	// FlagGetFlagSnapshotsHandler sets the operation handler for the get flag snapshots operation
	FlagGetFlagSnapshotsHandler flag.GetFlagSnapshotsHandler
	// HealthGetHealthHandler sets the operation handler for the get health operation
	HealthGetHealthHandler health.GetHealthHandler
	// EvaluationPostEvaluationHandler sets the operation handler for the post evaluation operation
	EvaluationPostEvaluationHandler evaluation.PostEvaluationHandler
	// EvaluationPostEvaluationBatchHandler sets the operation handler for the post evaluation batch operation
	EvaluationPostEvaluationBatchHandler evaluation.PostEvaluationBatchHandler
	// ConstraintPutConstraintHandler sets the operation handler for the put constraint operation
	ConstraintPutConstraintHandler constraint.PutConstraintHandler
	// DistributionPutDistributionsHandler sets the operation handler for the put distributions operation
	DistributionPutDistributionsHandler distribution.PutDistributionsHandler
	// FlagPutFlagHandler sets the operation handler for the put flag operation
	FlagPutFlagHandler flag.PutFlagHandler
	// SegmentPutSegmentHandler sets the operation handler for the put segment operation
	SegmentPutSegmentHandler segment.PutSegmentHandler
	// SegmentPutSegmentsReorderHandler sets the operation handler for the put segments reorder operation
	SegmentPutSegmentsReorderHandler segment.PutSegmentsReorderHandler
	// VariantPutVariantHandler sets the operation handler for the put variant operation
	VariantPutVariantHandler variant.PutVariantHandler
	// FlagRestoreFlagHandler sets the operation handler for the restore flag operation
	FlagRestoreFlagHandler flag.RestoreFlagHandler
	// FlagSetFlagEnabledHandler sets the operation handler for the set flag enabled operation
	FlagSetFlagEnabledHandler flag.SetFlagEnabledHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...any)
}

// UseRedoc for documentation at /docs
func (o *FlagrAPI) UseRedoc() { _ = "STUB: not implemented"; return }

// UseSwaggerUI for documentation at /docs
func (o *FlagrAPI) UseSwaggerUI() { _ = "STUB: not implemented"; return }

// SetDefaultProduces sets the default produces media type
func (o *FlagrAPI) SetDefaultProduces(mediaType string) { _ = "STUB: not implemented"; return }

// SetDefaultConsumes returns the default consumes media type
func (o *FlagrAPI) SetDefaultConsumes(mediaType string) { _ = "STUB: not implemented"; return }

// SetSpec sets a spec that will be served for the clients.
func (o *FlagrAPI) SetSpec(spec *loads.Document) {
	_ = "STUB: not implemented"

	// DefaultProduces returns the default produces media type
	return
}

func (o *FlagrAPI) DefaultProduces() string { _ = "STUB: not implemented"; return "" }

// DefaultConsumes returns the default consumes media type
func (o *FlagrAPI) DefaultConsumes() string { _ = "STUB: not implemented"; return "" }

// Formats returns the registered string formats
func (o *FlagrAPI) Formats() strfmt.Registry {
	_ = "STUB: not implemented"

	// RegisterFormat registers a custom format validator
	return *new(strfmt.Registry)
}

func (o *FlagrAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	_ = "STUB: not implemented"
	return
}

// Validate validates the registrations in the FlagrAPI
func (o *FlagrAPI) Validate() error { _ = "STUB: not implemented"; return nil }

// ServeErrorFor gets a error handler for a given operation id
func (o *FlagrAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	_ = "STUB: not implemented"
	return nil

	// AuthenticatorsFor gets the authenticators for the specified security schemes
}

func (o *FlagrAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	_ = "STUB: not implemented"

	// Authorizer returns the registered authorizer
	return nil
}

func (o *FlagrAPI) Authorizer() runtime.Authorizer {
	_ = "STUB: not implemented"

	// ConsumersFor gets the consumers for the specified media types.
	//
	// MIME type parameters are ignored here.
	return *new(runtime.Authorizer)
}

func (o *FlagrAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	_ = "STUB: not implemented"
	return nil
}

// ProducersFor gets the producers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *FlagrAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	_ = "STUB: not implemented"
	return nil
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *FlagrAPI) HandlerFor(method, path string) (http.Handler, bool) {
	_ = "STUB: not implemented"
	return *new(http.Handler), false
}

// Context returns the middleware context for the flagr API
func (o *FlagrAPI) Context() *middleware.Context { _ = "STUB: not implemented"; return nil }

func (o *FlagrAPI) initHandlerCache() {
	_ = "STUB: not implemented"
	// don't care about the result, just that the initialization happened
	return
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *FlagrAPI) Serve(builder middleware.Builder) http.Handler {
	_ = "STUB: not implemented"
	return *new(http.Handler)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *FlagrAPI) Init() { _ = "STUB: not implemented"; return }

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *FlagrAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	_ = "STUB: not implemented"
	return
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *FlagrAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *FlagrAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	_ = "STUB: not implemented"
	return
}
