// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewCreateFlagParams creates a new CreateFlagParams object
//
// There are no default values defined in the spec.
func NewCreateFlagParams() CreateFlagParams {
	_ = "STUB: not implemented"
	return *new(CreateFlagParams)
}

// CreateFlagParams contains all the bound params for the create flag operation
// typically these are obtained from a http.Request
//
// swagger:parameters createFlag
type CreateFlagParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*create a flag
	  Required: true
	  In: body
	*/
	Body *models.CreateFlagRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateFlagParams() beforehand.
func (o *CreateFlagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object
