// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateFlagHandlerFunc turns a function with the right signature into a create flag handler
type CreateFlagHandlerFunc func(CreateFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateFlagHandlerFunc) Handle(params CreateFlagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// CreateFlagHandler interface for that can handle valid create flag params
	return *new(middleware.Responder)
}

type CreateFlagHandler interface {
	Handle(CreateFlagParams) middleware.Responder
}

// NewCreateFlag creates a new http.Handler for the create flag operation
func NewCreateFlag(ctx *middleware.Context, handler CreateFlagHandler) *CreateFlag {
	_ = "STUB: not implemented"
	return nil
}

/*
	CreateFlag swagger:route POST /flags flag createFlag

CreateFlag create flag API
*/
type CreateFlag struct {
	Context *middleware.Context
	Handler CreateFlagHandler
}

func (o *CreateFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
