// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeleteFlagOKCode is the HTTP code returned for type DeleteFlagOK
const DeleteFlagOKCode int = 200

/*
DeleteFlagOK OK deleted

swagger:response deleteFlagOK
*/
type DeleteFlagOK struct {
}

// NewDeleteFlagOK creates DeleteFlagOK with default headers values
func NewDeleteFlagOK() *DeleteFlagOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *DeleteFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
DeleteFlagDefault generic error response

swagger:response deleteFlagDefault
*/
type DeleteFlagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteFlagDefault creates DeleteFlagDefault with default headers values
func NewDeleteFlagDefault(code int) *DeleteFlagDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the delete flag default response
func (o *DeleteFlagDefault) WithStatusCode(code int) *DeleteFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the delete flag default response
func (o *DeleteFlagDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the delete flag default response
func (o *DeleteFlagDefault) WithPayload(payload *models.Error) *DeleteFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the delete flag default response
func (o *DeleteFlagDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *DeleteFlagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
