// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteFlagHandlerFunc turns a function with the right signature into a delete flag handler
type DeleteFlagHandlerFunc func(DeleteFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFlagHandlerFunc) Handle(params DeleteFlagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteFlagHandler interface for that can handle valid delete flag params
	return *new(middleware.Responder)
}

type DeleteFlagHandler interface {
	Handle(DeleteFlagParams) middleware.Responder
}

// NewDeleteFlag creates a new http.Handler for the delete flag operation
func NewDeleteFlag(ctx *middleware.Context, handler DeleteFlagHandler) *DeleteFlag {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteFlag swagger:route DELETE /flags/{flagID} flag deleteFlag

DeleteFlag delete flag API
*/
type DeleteFlag struct {
	Context *middleware.Context
	Handler DeleteFlagHandler
}

func (o *DeleteFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
