// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewFindFlagsParams creates a new FindFlagsParams object
//
// There are no default values defined in the spec.
func NewFindFlagsParams() FindFlagsParams {
	_ = "STUB: not implemented"
	return *

	// FindFlagsParams contains all the bound params for the find flags operation
	// typically these are obtained from a http.Request
	//
	// swagger:parameters findFlags
	new(FindFlagsParams)
}

type FindFlagsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*return all deleted flags
	  In: query
	*/
	Deleted *bool

	/*return flags exactly matching given description
	  In: query
	*/
	Description *string

	/*return flags partially matching given description
	  In: query
	*/
	DescriptionLike *string

	/*return flags having given enabled status
	  In: query
	*/
	Enabled *bool

	/*return flags matching given key
	  In: query
	*/
	Key *string

	/*the numbers of flags to return
	  In: query
	*/
	Limit *int64

	/*return flags given the offset, it should usually set together with limit
	  In: query
	*/
	Offset *int64

	/*return flags with preloaded segments and variants
	  In: query
	*/
	Preload *bool

	/*return flags with the given tags (comma separated)
	  In: query
	*/
	Tags *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewFindFlagsParams() beforehand.
func (o *FindFlagsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindDeleted binds and validates parameter Deleted from query.
func (o *FindFlagsParams) bindDeleted(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindDescription binds and validates parameter Description from query.
func (o *FindFlagsParams) bindDescription(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindDescriptionLike binds and validates parameter DescriptionLike from query.
func (o *FindFlagsParams) bindDescriptionLike(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindEnabled binds and validates parameter Enabled from query.
func (o *FindFlagsParams) bindEnabled(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindKey binds and validates parameter Key from query.
func (o *FindFlagsParams) bindKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindLimit binds and validates parameter Limit from query.
func (o *FindFlagsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindOffset binds and validates parameter Offset from query.
func (o *FindFlagsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindPreload binds and validates parameter Preload from query.
func (o *FindFlagsParams) bindPreload(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindTags binds and validates parameter Tags from query.
func (o *FindFlagsParams) bindTags(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations
