// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindFlagsHandlerFunc turns a function with the right signature into a find flags handler
type FindFlagsHandlerFunc func(FindFlagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindFlagsHandlerFunc) Handle(params FindFlagsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// FindFlagsHandler interface for that can handle valid find flags params
	return *new(middleware.Responder)
}

type FindFlagsHandler interface {
	Handle(FindFlagsParams) middleware.Responder
}

// NewFindFlags creates a new http.Handler for the find flags operation
func NewFindFlags(ctx *middleware.Context, handler FindFlagsHandler) *FindFlags {
	_ = "STUB: not implemented"
	return nil
}

/*
	FindFlags swagger:route GET /flags flag findFlags

FindFlags find flags API
*/
type FindFlags struct {
	Context *middleware.Context
	Handler FindFlagsHandler
}

func (o *FindFlags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
