// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindFlagsOKCode is the HTTP code returned for type FindFlagsOK
const FindFlagsOKCode int = 200

/*
FindFlagsOK list all the flags

swagger:response findFlagsOK
*/
type FindFlagsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Flag `json:"body,omitempty"`
}

// NewFindFlagsOK creates FindFlagsOK with default headers values
func NewFindFlagsOK() *FindFlagsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find flags o k response
func (o *FindFlagsOK) WithPayload(payload []*models.Flag) *FindFlagsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find flags o k response
func (o *FindFlagsOK) SetPayload(payload []*models.Flag) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindFlagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindFlagsDefault generic error response

swagger:response findFlagsDefault
*/
type FindFlagsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindFlagsDefault creates FindFlagsDefault with default headers values
func NewFindFlagsDefault(code int) *FindFlagsDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the find flags default response
func (o *FindFlagsDefault) WithStatusCode(code int) *FindFlagsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find flags default response
func (o *FindFlagsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find flags default response
func (o *FindFlagsDefault) WithPayload(payload *models.Error) *FindFlagsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find flags default response
func (o *FindFlagsDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindFlagsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
