// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFlagSnapshotsHandlerFunc turns a function with the right signature into a get flag snapshots handler
type GetFlagSnapshotsHandlerFunc func(GetFlagSnapshotsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFlagSnapshotsHandlerFunc) Handle(params GetFlagSnapshotsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetFlagSnapshotsHandler interface for that can handle valid get flag snapshots params
	return *new(middleware.Responder)
}

type GetFlagSnapshotsHandler interface {
	Handle(GetFlagSnapshotsParams) middleware.Responder
}

// NewGetFlagSnapshots creates a new http.Handler for the get flag snapshots operation
func NewGetFlagSnapshots(ctx *middleware.Context, handler GetFlagSnapshotsHandler) *GetFlagSnapshots {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetFlagSnapshots swagger:route GET /flags/{flagID}/snapshots flag getFlagSnapshots

GetFlagSnapshots get flag snapshots API
*/
type GetFlagSnapshots struct {
	Context *middleware.Context
	Handler GetFlagSnapshotsHandler
}

func (o *GetFlagSnapshots) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
