// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetFlagSnapshotsOKCode is the HTTP code returned for type GetFlagSnapshotsOK
const GetFlagSnapshotsOKCode int = 200

/*
GetFlagSnapshotsOK returns the flag snapshots

swagger:response getFlagSnapshotsOK
*/
type GetFlagSnapshotsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.FlagSnapshot `json:"body,omitempty"`
}

// NewGetFlagSnapshotsOK creates GetFlagSnapshotsOK with default headers values
func NewGetFlagSnapshotsOK() *GetFlagSnapshotsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the get flag snapshots o k response
func (o *GetFlagSnapshotsOK) WithPayload(payload []*models.FlagSnapshot) *GetFlagSnapshotsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get flag snapshots o k response
func (o *GetFlagSnapshotsOK) SetPayload(payload []*models.FlagSnapshot) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetFlagSnapshotsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
GetFlagSnapshotsDefault generic error response

swagger:response getFlagSnapshotsDefault
*/
type GetFlagSnapshotsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFlagSnapshotsDefault creates GetFlagSnapshotsDefault with default headers values
func NewGetFlagSnapshotsDefault(code int) *GetFlagSnapshotsDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the get flag snapshots default response
func (o *GetFlagSnapshotsDefault) WithStatusCode(code int) *GetFlagSnapshotsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the get flag snapshots default response
func (o *GetFlagSnapshotsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the get flag snapshots default response
func (o *GetFlagSnapshotsDefault) WithPayload(payload *models.Error) *GetFlagSnapshotsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get flag snapshots default response
func (o *GetFlagSnapshotsDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetFlagSnapshotsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
