// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFlagHandlerFunc turns a function with the right signature into a get flag handler
type GetFlagHandlerFunc func(GetFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFlagHandlerFunc) Handle(params GetFlagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetFlagHandler interface for that can handle valid get flag params
	return *new(middleware.Responder)
}

type GetFlagHandler interface {
	Handle(GetFlagParams) middleware.Responder
}

// NewGetFlag creates a new http.Handler for the get flag operation
func NewGetFlag(ctx *middleware.Context, handler GetFlagHandler) *GetFlag {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetFlag swagger:route GET /flags/{flagID} flag getFlag

GetFlag get flag API
*/
type GetFlag struct {
	Context *middleware.Context
	Handler GetFlagHandler
}

func (o *GetFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
