// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetFlagSnapshotsParams creates a new GetFlagSnapshotsParams object
//
// There are no default values defined in the spec.
func NewGetFlagSnapshotsParams() GetFlagSnapshotsParams {
	_ = "STUB: not implemented"
	return *new(GetFlagSnapshotsParams)
}

// GetFlagSnapshotsParams contains all the bound params for the get flag snapshots operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFlagSnapshots
type GetFlagSnapshotsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*numeric ID of the flag to get
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*the number of snapshots to return
	  In: query
	*/
	Limit *int64

	/*return snapshots given the offset, it should usually set together with limit
	  In: query
	*/
	Offset *int64

	/*sort order
	  In: query
	*/
	Sort *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFlagSnapshotsParams() beforehand.
func (o *GetFlagSnapshotsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindFlagID binds and validates parameter FlagID from path.
func (o *GetFlagSnapshotsParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *GetFlagSnapshotsParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetFlagSnapshotsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindOffset binds and validates parameter Offset from query.
func (o *GetFlagSnapshotsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// bindSort binds and validates parameter Sort from query.
func (o *GetFlagSnapshotsParams) bindSort(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: false
// AllowEmptyValue: false

// empty values pass all other validations

// validateSort carries out validations for parameter Sort
func (o *GetFlagSnapshotsParams) validateSort(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
