// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetFlagEntityTypesOKCode is the HTTP code returned for type GetFlagEntityTypesOK
const GetFlagEntityTypesOKCode int = 200

/*
GetFlagEntityTypesOK returns all the FlagEntityTypes

swagger:response getFlagEntityTypesOK
*/
type GetFlagEntityTypesOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetFlagEntityTypesOK creates GetFlagEntityTypesOK with default headers values
func NewGetFlagEntityTypesOK() *GetFlagEntityTypesOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the get flag entity types o k response
func (o *GetFlagEntityTypesOK) WithPayload(payload []string) *GetFlagEntityTypesOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get flag entity types o k response
func (o *GetFlagEntityTypesOK) SetPayload(payload []string) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *GetFlagEntityTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
GetFlagEntityTypesDefault generic error response

swagger:response getFlagEntityTypesDefault
*/
type GetFlagEntityTypesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFlagEntityTypesDefault creates GetFlagEntityTypesDefault with default headers values
func NewGetFlagEntityTypesDefault(code int) *GetFlagEntityTypesDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the get flag entity types default response
func (o *GetFlagEntityTypesDefault) WithStatusCode(code int) *GetFlagEntityTypesDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the get flag entity types default response
func (o *GetFlagEntityTypesDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the get flag entity types default response
func (o *GetFlagEntityTypesDefault) WithPayload(payload *models.Error) *GetFlagEntityTypesDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get flag entity types default response
func (o *GetFlagEntityTypesDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetFlagEntityTypesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
