// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutFlagOKCode is the HTTP code returned for type PutFlagOK
const PutFlagOKCode int = 200

/*
PutFlagOK returns the flag

swagger:response putFlagOK
*/
type PutFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.Flag `json:"body,omitempty"`
}

// NewPutFlagOK creates PutFlagOK with default headers values
func NewPutFlagOK() *PutFlagOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the put flag o k response
func (o *PutFlagOK) WithPayload(payload *models.Flag) *PutFlagOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put flag o k response
func (o *PutFlagOK) SetPayload(payload *models.Flag) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
PutFlagDefault generic error response

swagger:response putFlagDefault
*/
type PutFlagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutFlagDefault creates PutFlagDefault with default headers values
func NewPutFlagDefault(code int) *PutFlagDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the put flag default response
func (o *PutFlagDefault) WithStatusCode(code int) *PutFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put flag default response
func (o *PutFlagDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put flag default response
func (o *PutFlagDefault) WithPayload(payload *models.Error) *PutFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put flag default response
func (o *PutFlagDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutFlagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
