// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutFlagHandlerFunc turns a function with the right signature into a put flag handler
type PutFlagHandlerFunc func(PutFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutFlagHandlerFunc) Handle(params PutFlagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutFlagHandler interface for that can handle valid put flag params
	return *new(middleware.Responder)
}

type PutFlagHandler interface {
	Handle(PutFlagParams) middleware.Responder
}

// NewPutFlag creates a new http.Handler for the put flag operation
func NewPutFlag(ctx *middleware.Context, handler PutFlagHandler) *PutFlag {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutFlag swagger:route PUT /flags/{flagID} flag putFlag

PutFlag put flag API
*/
type PutFlag struct {
	Context *middleware.Context
	Handler PutFlagHandler
}

func (o *PutFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
