// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/url"
)

// PutFlagURL generates an URL for the put flag operation
type PutFlagURL struct {
	FlagID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutFlagURL) WithBasePath(bp string) *PutFlagURL { _ = "STUB: not implemented"; return nil }

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PutFlagURL) SetBasePath(bp string) {
	_ = "STUB: not implemented"

	// Build a url path and query string
	return
}

func (o *PutFlagURL) Build() (*url.URL, error) { _ = "STUB: not implemented"; return nil, nil }

// Must is a helper function to panic when the url builder returns an error
func (o *PutFlagURL) Must(u *url.URL, err error) *url.URL { _ = "STUB: not implemented"; return nil }

// String returns the string representation of the path with query string
func (o *PutFlagURL) String() string { _ = "STUB: not implemented"; return "" }

// BuildFull builds a full url with scheme, host, path and query string
func (o *PutFlagURL) BuildFull(scheme, host string) (*url.URL, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StringFull returns the string representation of a complete url
func (o *PutFlagURL) StringFull(scheme, host string) string { _ = "STUB: not implemented"; return "" }
