// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// RestoreFlagOKCode is the HTTP code returned for type RestoreFlagOK
const RestoreFlagOKCode int = 200

/*
RestoreFlagOK returns the flag

swagger:response restoreFlagOK
*/
type RestoreFlagOK struct {

	/*
	  In: Body
	*/
	Payload *models.Flag `json:"body,omitempty"`
}

// NewRestoreFlagOK creates RestoreFlagOK with default headers values
func NewRestoreFlagOK() *RestoreFlagOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the restore flag o k response
func (o *RestoreFlagOK) WithPayload(payload *models.Flag) *RestoreFlagOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the restore flag o k response
func (o *RestoreFlagOK) SetPayload(payload *models.Flag) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *RestoreFlagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
RestoreFlagDefault generic error response

swagger:response restoreFlagDefault
*/
type RestoreFlagDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRestoreFlagDefault creates RestoreFlagDefault with default headers values
func NewRestoreFlagDefault(code int) *RestoreFlagDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the restore flag default response
func (o *RestoreFlagDefault) WithStatusCode(code int) *RestoreFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the restore flag default response
func (o *RestoreFlagDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the restore flag default response
func (o *RestoreFlagDefault) WithPayload(payload *models.Error) *RestoreFlagDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the restore flag default response
func (o *RestoreFlagDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *RestoreFlagDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
