// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RestoreFlagHandlerFunc turns a function with the right signature into a restore flag handler
type RestoreFlagHandlerFunc func(RestoreFlagParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RestoreFlagHandlerFunc) Handle(params RestoreFlagParams) middleware.Responder {
	_ = "STUB: not implemented"

	// RestoreFlagHandler interface for that can handle valid restore flag params
	return *new(middleware.Responder)
}

type RestoreFlagHandler interface {
	Handle(RestoreFlagParams) middleware.Responder
}

// NewRestoreFlag creates a new http.Handler for the restore flag operation
func NewRestoreFlag(ctx *middleware.Context, handler RestoreFlagHandler) *RestoreFlag {
	_ = "STUB: not implemented"
	return nil
}

/*
	RestoreFlag swagger:route PUT /flags/{flagID}/restore flag restoreFlag

RestoreFlag restore flag API
*/
type RestoreFlag struct {
	Context *middleware.Context
	Handler RestoreFlagHandler
}

func (o *RestoreFlag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
