// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SetFlagEnabledHandlerFunc turns a function with the right signature into a set flag enabled handler
type SetFlagEnabledHandlerFunc func(SetFlagEnabledParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SetFlagEnabledHandlerFunc) Handle(params SetFlagEnabledParams) middleware.Responder {
	_ = "STUB: not implemented"

	// SetFlagEnabledHandler interface for that can handle valid set flag enabled params
	return *new(middleware.Responder)
}

type SetFlagEnabledHandler interface {
	Handle(SetFlagEnabledParams) middleware.Responder
}

// NewSetFlagEnabled creates a new http.Handler for the set flag enabled operation
func NewSetFlagEnabled(ctx *middleware.Context, handler SetFlagEnabledHandler) *SetFlagEnabled {
	_ = "STUB: not implemented"
	return nil
}

/*
	SetFlagEnabled swagger:route PUT /flags/{flagID}/enabled flag setFlagEnabled

SetFlagEnabled set flag enabled API
*/
type SetFlagEnabled struct {
	Context *middleware.Context
	Handler SetFlagEnabledHandler
}

func (o *SetFlagEnabled) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
