// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// SetFlagEnabledOKCode is the HTTP code returned for type SetFlagEnabledOK
const SetFlagEnabledOKCode int = 200

/*
SetFlagEnabledOK returns the flag

swagger:response setFlagEnabledOK
*/
type SetFlagEnabledOK struct {

	/*
	  In: Body
	*/
	Payload *models.Flag `json:"body,omitempty"`
}

// NewSetFlagEnabledOK creates SetFlagEnabledOK with default headers values
func NewSetFlagEnabledOK() *SetFlagEnabledOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the set flag enabled o k response
func (o *SetFlagEnabledOK) WithPayload(payload *models.Flag) *SetFlagEnabledOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the set flag enabled o k response
func (o *SetFlagEnabledOK) SetPayload(payload *models.Flag) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *SetFlagEnabledOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
SetFlagEnabledDefault generic error response

swagger:response setFlagEnabledDefault
*/
type SetFlagEnabledDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetFlagEnabledDefault creates SetFlagEnabledDefault with default headers values
func NewSetFlagEnabledDefault(code int) *SetFlagEnabledDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the set flag enabled default response
func (o *SetFlagEnabledDefault) WithStatusCode(code int) *SetFlagEnabledDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the set flag enabled default response
func (o *SetFlagEnabledDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the set flag enabled default response
func (o *SetFlagEnabledDefault) WithPayload(payload *models.Error) *SetFlagEnabledDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the set flag enabled default response
func (o *SetFlagEnabledDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *SetFlagEnabledDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
