// Code generated by go-swagger; DO NOT EDIT.

package flag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewSetFlagEnabledParams creates a new SetFlagEnabledParams object
//
// There are no default values defined in the spec.
func NewSetFlagEnabledParams() SetFlagEnabledParams {
	_ = "STUB: not implemented"
	return *new(SetFlagEnabledParams)
}

// SetFlagEnabledParams contains all the bound params for the set flag enabled operation
// typically these are obtained from a http.Request
//
// swagger:parameters setFlagEnabled
type SetFlagEnabledParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*set flag enabled state
	  Required: true
	  In: body
	*/
	Body *models.SetFlagEnabledRequest

	/*numeric ID of the flag to get
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSetFlagEnabledParams() beforehand.
func (o *SetFlagEnabledParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object

// bindFlagID binds and validates parameter FlagID from path.
func (o *SetFlagEnabledParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *SetFlagEnabledParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
