// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// CreateSegmentOKCode is the HTTP code returned for type CreateSegmentOK
const CreateSegmentOKCode int = 200

/*
CreateSegmentOK segment created

swagger:response createSegmentOK
*/
type CreateSegmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Segment `json:"body,omitempty"`
}

// NewCreateSegmentOK creates CreateSegmentOK with default headers values
func NewCreateSegmentOK() *CreateSegmentOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the create segment o k response
func (o *CreateSegmentOK) WithPayload(payload *models.Segment) *CreateSegmentOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the create segment o k response
func (o *CreateSegmentOK) SetPayload(payload *models.Segment) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *CreateSegmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
CreateSegmentDefault generic error response

swagger:response createSegmentDefault
*/
type CreateSegmentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateSegmentDefault creates CreateSegmentDefault with default headers values
func NewCreateSegmentDefault(code int) *CreateSegmentDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the create segment default response
func (o *CreateSegmentDefault) WithStatusCode(code int) *CreateSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the create segment default response
func (o *CreateSegmentDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the create segment default response
func (o *CreateSegmentDefault) WithPayload(payload *models.Error) *CreateSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the create segment default response
func (o *CreateSegmentDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *CreateSegmentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
