// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSegmentHandlerFunc turns a function with the right signature into a delete segment handler
type DeleteSegmentHandlerFunc func(DeleteSegmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSegmentHandlerFunc) Handle(params DeleteSegmentParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteSegmentHandler interface for that can handle valid delete segment params
	return *new(middleware.Responder)
}

type DeleteSegmentHandler interface {
	Handle(DeleteSegmentParams) middleware.Responder
}

// NewDeleteSegment creates a new http.Handler for the delete segment operation
func NewDeleteSegment(ctx *middleware.Context, handler DeleteSegmentHandler) *DeleteSegment {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteSegment swagger:route DELETE /flags/{flagID}/segments/{segmentID} segment deleteSegment

DeleteSegment delete segment API
*/
type DeleteSegment struct {
	Context *middleware.Context
	Handler DeleteSegmentHandler
}

func (o *DeleteSegment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
