// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeleteSegmentOKCode is the HTTP code returned for type DeleteSegmentOK
const DeleteSegmentOKCode int = 200

/*
DeleteSegmentOK deleted

swagger:response deleteSegmentOK
*/
type DeleteSegmentOK struct {
}

// NewDeleteSegmentOK creates DeleteSegmentOK with default headers values
func NewDeleteSegmentOK() *DeleteSegmentOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *DeleteSegmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
DeleteSegmentDefault generic error response

swagger:response deleteSegmentDefault
*/
type DeleteSegmentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSegmentDefault creates DeleteSegmentDefault with default headers values
func NewDeleteSegmentDefault(code int) *DeleteSegmentDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the delete segment default response
func (o *DeleteSegmentDefault) WithStatusCode(code int) *DeleteSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the delete segment default response
func (o *DeleteSegmentDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the delete segment default response
func (o *DeleteSegmentDefault) WithPayload(payload *models.Error) *DeleteSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the delete segment default response
func (o *DeleteSegmentDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *DeleteSegmentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
