// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindSegmentsOKCode is the HTTP code returned for type FindSegmentsOK
const FindSegmentsOKCode int = 200

/*
FindSegmentsOK segments ordered by rank of the flag

swagger:response findSegmentsOK
*/
type FindSegmentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Segment `json:"body,omitempty"`
}

// NewFindSegmentsOK creates FindSegmentsOK with default headers values
func NewFindSegmentsOK() *FindSegmentsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find segments o k response
func (o *FindSegmentsOK) WithPayload(payload []*models.Segment) *FindSegmentsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find segments o k response
func (o *FindSegmentsOK) SetPayload(payload []*models.Segment) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindSegmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindSegmentsDefault generic error response

swagger:response findSegmentsDefault
*/
type FindSegmentsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindSegmentsDefault creates FindSegmentsDefault with default headers values
func NewFindSegmentsDefault(code int) *FindSegmentsDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the find segments default response
func (o *FindSegmentsDefault) WithStatusCode(code int) *FindSegmentsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find segments default response
func (o *FindSegmentsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find segments default response
func (o *FindSegmentsDefault) WithPayload(payload *models.Error) *FindSegmentsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find segments default response
func (o *FindSegmentsDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *FindSegmentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
