// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindSegmentsHandlerFunc turns a function with the right signature into a find segments handler
type FindSegmentsHandlerFunc func(FindSegmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindSegmentsHandlerFunc) Handle(params FindSegmentsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// FindSegmentsHandler interface for that can handle valid find segments params
	return *new(middleware.Responder)
}

type FindSegmentsHandler interface {
	Handle(FindSegmentsParams) middleware.Responder
}

// NewFindSegments creates a new http.Handler for the find segments operation
func NewFindSegments(ctx *middleware.Context, handler FindSegmentsHandler) *FindSegments {
	_ = "STUB: not implemented"
	return nil
}

/*
	FindSegments swagger:route GET /flags/{flagID}/segments segment findSegments

FindSegments find segments API
*/
type FindSegments struct {
	Context *middleware.Context
	Handler FindSegmentsHandler
}

func (o *FindSegments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
