// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutSegmentsReorderHandlerFunc turns a function with the right signature into a put segments reorder handler
type PutSegmentsReorderHandlerFunc func(PutSegmentsReorderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSegmentsReorderHandlerFunc) Handle(params PutSegmentsReorderParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutSegmentsReorderHandler interface for that can handle valid put segments reorder params
	return *new(middleware.Responder)
}

type PutSegmentsReorderHandler interface {
	Handle(PutSegmentsReorderParams) middleware.Responder
}

// NewPutSegmentsReorder creates a new http.Handler for the put segments reorder operation
func NewPutSegmentsReorder(ctx *middleware.Context, handler PutSegmentsReorderHandler) *PutSegmentsReorder {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutSegmentsReorder swagger:route PUT /flags/{flagID}/segments/reorder segment putSegmentsReorder

PutSegmentsReorder put segments reorder API
*/
type PutSegmentsReorder struct {
	Context *middleware.Context
	Handler PutSegmentsReorderHandler
}

func (o *PutSegmentsReorder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
