// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutSegmentsReorderOKCode is the HTTP code returned for type PutSegmentsReorderOK
const PutSegmentsReorderOKCode int = 200

/*
PutSegmentsReorderOK segments reordered

swagger:response putSegmentsReorderOK
*/
type PutSegmentsReorderOK struct {
}

// NewPutSegmentsReorderOK creates PutSegmentsReorderOK with default headers values
func NewPutSegmentsReorderOK() *PutSegmentsReorderOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *PutSegmentsReorderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
PutSegmentsReorderDefault generic error response

swagger:response putSegmentsReorderDefault
*/
type PutSegmentsReorderDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutSegmentsReorderDefault creates PutSegmentsReorderDefault with default headers values
func NewPutSegmentsReorderDefault(code int) *PutSegmentsReorderDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the put segments reorder default response
func (o *PutSegmentsReorderDefault) WithStatusCode(code int) *PutSegmentsReorderDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put segments reorder default response
func (o *PutSegmentsReorderDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put segments reorder default response
func (o *PutSegmentsReorderDefault) WithPayload(payload *models.Error) *PutSegmentsReorderDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put segments reorder default response
func (o *PutSegmentsReorderDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *PutSegmentsReorderDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
