// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewPutSegmentParams creates a new PutSegmentParams object
//
// There are no default values defined in the spec.
func NewPutSegmentParams() PutSegmentParams {
	_ = "STUB: not implemented"
	return *new(PutSegmentParams)
}

// PutSegmentParams contains all the bound params for the put segment operation
// typically these are obtained from a http.Request
//
// swagger:parameters putSegment
type PutSegmentParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*update a segment
	  Required: true
	  In: body
	*/
	Body *models.PutSegmentRequest

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the segment
	  Required: true
	  Minimum: 1
	  In: path
	*/
	SegmentID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutSegmentParams() beforehand.
func (o *PutSegmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object

// bindFlagID binds and validates parameter FlagID from path.
func (o *PutSegmentParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *PutSegmentParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindSegmentID binds and validates parameter SegmentID from path.
func (o *PutSegmentParams) bindSegmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateSegmentID carries out validations for parameter SegmentID
func (o *PutSegmentParams) validateSegmentID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
