// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutSegmentOKCode is the HTTP code returned for type PutSegmentOK
const PutSegmentOKCode int = 200

/*
PutSegmentOK segment updated

swagger:response putSegmentOK
*/
type PutSegmentOK struct {

	/*
	  In: Body
	*/
	Payload *models.Segment `json:"body,omitempty"`
}

// NewPutSegmentOK creates PutSegmentOK with default headers values
func NewPutSegmentOK() *PutSegmentOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the put segment o k response
func (o *PutSegmentOK) WithPayload(payload *models.Segment) *PutSegmentOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put segment o k response
func (o *PutSegmentOK) SetPayload(payload *models.Segment) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutSegmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
PutSegmentDefault generic error response

swagger:response putSegmentDefault
*/
type PutSegmentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutSegmentDefault creates PutSegmentDefault with default headers values
func NewPutSegmentDefault(code int) *PutSegmentDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the put segment default response
func (o *PutSegmentDefault) WithStatusCode(code int) *PutSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put segment default response
func (o *PutSegmentDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put segment default response
func (o *PutSegmentDefault) WithPayload(payload *models.Error) *PutSegmentDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put segment default response
func (o *PutSegmentDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutSegmentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
