// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutSegmentHandlerFunc turns a function with the right signature into a put segment handler
type PutSegmentHandlerFunc func(PutSegmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSegmentHandlerFunc) Handle(params PutSegmentParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutSegmentHandler interface for that can handle valid put segment params
	return *new(middleware.Responder)
}

type PutSegmentHandler interface {
	Handle(PutSegmentParams) middleware.Responder
}

// NewPutSegment creates a new http.Handler for the put segment operation
func NewPutSegment(ctx *middleware.Context, handler PutSegmentHandler) *PutSegment {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutSegment swagger:route PUT /flags/{flagID}/segments/{segmentID} segment putSegment

PutSegment put segment API
*/
type PutSegment struct {
	Context *middleware.Context
	Handler PutSegmentHandler
}

func (o *PutSegment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
