// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// Constraint constraint
//
// swagger:model constraint
type Constraint struct {

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// operator
	// Required: true
	// Min Length: 1
	// Enum: ["EQ","NEQ","LT","LTE","GT","GTE","EREG","NEREG","IN","NOTIN","CONTAINS","NOTCONTAINS"]
	Operator *string `json:"operator"`

	// The property name from the entity context to evaluate. Supports nested field access: use dots (e.g., `user.name`)  for nested objects and brackets (e.g., `users[0]`) for array indices.
	//
	// Required: true
	// Min Length: 1
	Property *string `json:"property"`

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this constraint
func (m *Constraint) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Constraint) validateID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

var constraintTypeOperatorPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["EQ","NEQ","LT","LTE","GT","GTE","EREG","NEREG","IN","NOTIN","CONTAINS","NOTCONTAINS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		constraintTypeOperatorPropEnum = append(constraintTypeOperatorPropEnum, v)
	}
}

const (

	// ConstraintOperatorEQ captures enum value "EQ"
	ConstraintOperatorEQ string = "EQ"

	// ConstraintOperatorNEQ captures enum value "NEQ"
	ConstraintOperatorNEQ string = "NEQ"

	// ConstraintOperatorLT captures enum value "LT"
	ConstraintOperatorLT string = "LT"

	// ConstraintOperatorLTE captures enum value "LTE"
	ConstraintOperatorLTE string = "LTE"

	// ConstraintOperatorGT captures enum value "GT"
	ConstraintOperatorGT string = "GT"

	// ConstraintOperatorGTE captures enum value "GTE"
	ConstraintOperatorGTE string = "GTE"

	// ConstraintOperatorEREG captures enum value "EREG"
	ConstraintOperatorEREG string = "EREG"

	// ConstraintOperatorNEREG captures enum value "NEREG"
	ConstraintOperatorNEREG string = "NEREG"

	// ConstraintOperatorIN captures enum value "IN"
	ConstraintOperatorIN string = "IN"

	// ConstraintOperatorNOTIN captures enum value "NOTIN"
	ConstraintOperatorNOTIN string = "NOTIN"

	// ConstraintOperatorCONTAINS captures enum value "CONTAINS"
	ConstraintOperatorCONTAINS string = "CONTAINS"

	// ConstraintOperatorNOTCONTAINS captures enum value "NOTCONTAINS"
	ConstraintOperatorNOTCONTAINS string = "NOTCONTAINS"
)

// prop value enum
func (m *Constraint) validateOperatorEnum(path, location string, value string) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Constraint) validateOperator(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// value enum

func (m *Constraint) validateProperty(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Constraint) validateValue(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this constraint based on the context it is used
func (m *Constraint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Constraint) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *Constraint) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Constraint) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
