// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreateVariantRequest create variant request
//
// swagger:model createVariantRequest
type CreateVariantRequest struct {

	// attachment
	Attachment any `json:"attachment,omitempty"`

	// key
	// Required: true
	// Min Length: 1
	Key *string `json:"key"`
}

// Validate validates this create variant request
func (m *CreateVariantRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateVariantRequest) validateKey(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this create variant request based on context it is used
func (m *CreateVariantRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CreateVariantRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CreateVariantRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
