// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreateConstraintRequest create constraint request
//
// swagger:model createConstraintRequest
type CreateConstraintRequest struct {

	// operator
	// Required: true
	// Min Length: 1
	Operator *string `json:"operator"`

	// The property name from the entity context to evaluate. Supports nested field access: use dots (e.g., `user.name`)  for nested objects and brackets (e.g., `users[0]`) for array indices.
	//
	// Required: true
	// Min Length: 1
	Property *string `json:"property"`

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this create constraint request
func (m *CreateConstraintRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateConstraintRequest) validateOperator(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateConstraintRequest) validateProperty(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateConstraintRequest) validateValue(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this create constraint request based on context it is used
func (m *CreateConstraintRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CreateConstraintRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CreateConstraintRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
