// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreateSegmentRequest create segment request
//
// swagger:model createSegmentRequest
type CreateSegmentRequest struct {

	// description
	// Required: true
	// Min Length: 1
	Description *string `json:"description"`

	// rollout percent
	// Required: true
	// Maximum: 100
	// Minimum: 0
	RolloutPercent *int64 `json:"rolloutPercent"`
}

// Validate validates this create segment request
func (m *CreateSegmentRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateSegmentRequest) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateSegmentRequest) validateRolloutPercent(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this create segment request based on context it is used
func (m *CreateSegmentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CreateSegmentRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CreateSegmentRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
