// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreateTagRequest create tag request
//
// swagger:model createTagRequest
type CreateTagRequest struct {

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this create tag request
func (m *CreateTagRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateTagRequest) validateValue(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this create tag request based on context it is used
func (m *CreateTagRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CreateTagRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CreateTagRequest) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
