// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CreateFlagRequest create flag request
//
// swagger:model createFlagRequest
type CreateFlagRequest struct {

	// description
	// Required: true
	// Min Length: 1
	Description *string `json:"description"`

	// unique key representation of the flag
	Key string `json:"key,omitempty"`

	// template for flag creation
	Template string `json:"template,omitempty"`
}

// Validate validates this create flag request
func (m *CreateFlagRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CreateFlagRequest) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this create flag request based on context it is used
func (m *CreateFlagRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CreateFlagRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CreateFlagRequest) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
