// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Distribution distribution
//
// swagger:model distribution
type Distribution struct {

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// percent
	// Required: true
	// Maximum: 100
	// Minimum: 0
	Percent *int64 `json:"percent"`

	// variant ID
	// Required: true
	// Minimum: 1
	VariantID *int64 `json:"variantID"`

	// variant key
	// Required: true
	// Min Length: 1
	VariantKey *string `json:"variantKey"`
}

// Validate validates this distribution
func (m *Distribution) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Distribution) validateID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *Distribution) validatePercent(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Distribution) validateVariantID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Distribution) validateVariantKey(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this distribution based on the context it is used
func (m *Distribution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Distribution) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *Distribution) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Distribution) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
