// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Error error
//
// swagger:model error
type Error struct {

	// message
	// Required: true
	// Min Length: 1
	Message *string `json:"message"`
}

// Validate validates this error
func (m *Error) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Error) validateMessage(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this error based on context it is used
func (m *Error) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *Error) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Error) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
