// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Flag flag
//
// swagger:model flag
type Flag struct {

	// created by
	CreatedBy string `json:"createdBy,omitempty"`

	// enabled data records will get data logging in the metrics pipeline, for example, kafka.
	// Required: true
	DataRecordsEnabled *bool `json:"dataRecordsEnabled"`

	// description
	// Required: true
	// Min Length: 1
	Description *string `json:"description"`

	// enabled
	// Required: true
	Enabled *bool `json:"enabled"`

	// it will override the entityType in the evaluation logs if it's not empty
	EntityType string `json:"entityType,omitempty"`

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// unique key representation of the flag
	// Min Length: 1
	Key string `json:"key,omitempty"`

	// flag usage details in markdown format
	Notes string `json:"notes,omitempty"`

	// segments
	Segments []*Segment `json:"segments"`

	// tags
	Tags []*Tag `json:"tags"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updatedAt,omitempty"`

	// updated by
	UpdatedBy string `json:"updatedBy,omitempty"`

	// variants
	Variants []*Variant `json:"variants"`
}

// Validate validates this flag
func (m *Flag) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Flag) validateDataRecordsEnabled(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Flag) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Flag) validateEnabled(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Flag) validateID(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

func (m *Flag) validateKey(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

func (m *Flag) validateSegments(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// not required

func (m *Flag) validateTags(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

// not required

func (m *Flag) validateUpdatedAt(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *Flag) validateVariants(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// not required

// ContextValidate validate this flag based on the context it is used
func (m *Flag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Flag) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Flag) contextValidateSegments(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *Flag) contextValidateTags(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *Flag) contextValidateVariants(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *Flag) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Flag) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
