// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// FlagSnapshot flag snapshot
//
// swagger:model flagSnapshot
type FlagSnapshot struct {

	// flag
	// Required: true
	Flag *Flag `json:"flag"`

	// id
	// Required: true
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id"`

	// updated at
	// Required: true
	// Min Length: 1
	UpdatedAt *string `json:"updatedAt"`

	// updated by
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// Validate validates this flag snapshot
func (m *FlagSnapshot) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *FlagSnapshot) validateFlag(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *FlagSnapshot) validateID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *FlagSnapshot) validateUpdatedAt(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this flag snapshot based on the context it is used
func (m *FlagSnapshot) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *FlagSnapshot) contextValidateFlag(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *FlagSnapshot) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *FlagSnapshot) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *FlagSnapshot) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
