// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Health health
//
// swagger:model health
type Health struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this health
func (m *Health) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this health based on context it is used
	return nil
}

func (m *Health) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *Health) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Health) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
