// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PutVariantRequest put variant request
//
// swagger:model putVariantRequest
type PutVariantRequest struct {

	// attachment
	Attachment any `json:"attachment,omitempty"`

	// key
	// Required: true
	// Min Length: 1
	Key *string `json:"key"`
}

// Validate validates this put variant request
func (m *PutVariantRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutVariantRequest) validateKey(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this put variant request based on context it is used
func (m *PutVariantRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *PutVariantRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *PutVariantRequest) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
