// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PutFlagRequest put flag request
//
// swagger:model putFlagRequest
type PutFlagRequest struct {

	// enabled data records will get data logging in the metrics pipeline, for example, kafka.
	DataRecordsEnabled *bool `json:"dataRecordsEnabled,omitempty"`

	// description
	// Min Length: 1
	Description *string `json:"description,omitempty"`

	// enabled
	Enabled *bool `json:"enabled,omitempty"`

	// it will overwrite entityType into evaluation logs if it's not empty
	EntityType *string `json:"entityType,omitempty"`

	// key
	Key *string `json:"key,omitempty"`

	// notes
	Notes *string `json:"notes,omitempty"`
}

// Validate validates this put flag request
func (m *PutFlagRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutFlagRequest) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// ContextValidate validates this put flag request based on context it is used
func (m *PutFlagRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *PutFlagRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *PutFlagRequest) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
