// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PutSegmentReorderRequest put segment reorder request
//
// swagger:model putSegmentReorderRequest
type PutSegmentReorderRequest struct {

	// segment i ds
	// Required: true
	// Min Items: 1
	SegmentIDs []int64 `json:"segmentIDs"`
}

// Validate validates this put segment reorder request
func (m *PutSegmentReorderRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutSegmentReorderRequest) validateSegmentIDs(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this put segment reorder request based on context it is used
func (m *PutSegmentReorderRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *PutSegmentReorderRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *PutSegmentReorderRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
