// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PutSegmentRequest put segment request
//
// swagger:model putSegmentRequest
type PutSegmentRequest struct {

	// description
	// Required: true
	// Min Length: 1
	Description *string `json:"description"`

	// rollout percent
	// Required: true
	// Maximum: 100
	// Minimum: 0
	RolloutPercent *int64 `json:"rolloutPercent"`
}

// Validate validates this put segment request
func (m *PutSegmentRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutSegmentRequest) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutSegmentRequest) validateRolloutPercent(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this put segment request based on context it is used
func (m *PutSegmentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *PutSegmentRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *PutSegmentRequest) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
