// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// PutDistributionsRequest put distributions request
//
// swagger:model putDistributionsRequest
type PutDistributionsRequest struct {

	// distributions
	// Required: true
	Distributions []*Distribution `json:"distributions"`
}

// Validate validates this put distributions request
func (m *PutDistributionsRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutDistributionsRequest) validateDistributions(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// ContextValidate validate this put distributions request based on the context it is used
func (m *PutDistributionsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *PutDistributionsRequest) contextValidateDistributions(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// MarshalBinary interface implementation
func (m *PutDistributionsRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *PutDistributionsRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
