// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SegmentDebugLog segment debug log
//
// swagger:model segmentDebugLog
type SegmentDebugLog struct {

	// msg
	Msg string `json:"msg,omitempty"`

	// segment ID
	// Minimum: 1
	SegmentID int64 `json:"segmentID,omitempty"`
}

// Validate validates this segment debug log
func (m *SegmentDebugLog) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SegmentDebugLog) validateSegmentID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// ContextValidate validates this segment debug log based on context it is used
func (m *SegmentDebugLog) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *SegmentDebugLog) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *SegmentDebugLog) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
