// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Segment segment
//
// swagger:model segment
type Segment struct {

	// constraints
	Constraints []*Constraint `json:"constraints"`

	// description
	// Required: true
	// Min Length: 1
	Description *string `json:"description"`

	// distributions
	Distributions []*Distribution `json:"distributions"`

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// rank
	// Required: true
	// Minimum: 0
	Rank *int64 `json:"rank"`

	// rollout percent
	// Required: true
	// Maximum: 100
	// Minimum: 0
	RolloutPercent *int64 `json:"rolloutPercent"`
}

// Validate validates this segment
func (m *Segment) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Segment) validateConstraints(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// not required

func (m *Segment) validateDescription(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Segment) validateDistributions(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

// not required

func (m *Segment) validateID(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

func (m *Segment) validateRank(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Segment) validateRolloutPercent(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this segment based on the context it is used
func (m *Segment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Segment) contextValidateConstraints(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *Segment) contextValidateDistributions(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *Segment) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *Segment) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Segment) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
