// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SetFlagEnabledRequest set flag enabled request
//
// swagger:model setFlagEnabledRequest
type SetFlagEnabledRequest struct {

	// enabled
	// Required: true
	Enabled *bool `json:"enabled"`
}

// Validate validates this set flag enabled request
func (m *SetFlagEnabledRequest) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SetFlagEnabledRequest) validateEnabled(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this set flag enabled request based on context it is used
func (m *SetFlagEnabledRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *SetFlagEnabledRequest) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *SetFlagEnabledRequest) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
