// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Tag tag
//
// swagger:model tag
type Tag struct {

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// value
	// Required: true
	// Min Length: 1
	Value *string `json:"value"`
}

// Validate validates this tag
func (m *Tag) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Tag) validateID(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

func (m *Tag) validateValue(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// ContextValidate validate this tag based on the context it is used
func (m *Tag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Tag) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *Tag) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Tag) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
