// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Variant variant
//
// swagger:model variant
type Variant struct {

	// attachment
	Attachment any `json:"attachment,omitempty"`

	// id
	// Read Only: true
	// Minimum: 1
	ID int64 `json:"id,omitempty"`

	// key
	// Required: true
	// Min Length: 1
	Key *string `json:"key"`
}

// Validate validates this variant
func (m *Variant) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Variant) validateID(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// not required

func (m *Variant) validateKey(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

// ContextValidate validate this variant based on the context it is used
func (m *Variant) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *Variant) contextValidateID(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *Variant) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Variant) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
