// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateConstraintHandlerFunc turns a function with the right signature into a create constraint handler
type CreateConstraintHandlerFunc func(CreateConstraintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateConstraintHandlerFunc) Handle(params CreateConstraintParams) middleware.Responder {
	_ = "STUB: not implemented"

	// CreateConstraintHandler interface for that can handle valid create constraint params
	return *new(middleware.Responder)
}

type CreateConstraintHandler interface {
	Handle(CreateConstraintParams) middleware.Responder
}

// NewCreateConstraint creates a new http.Handler for the create constraint operation
func NewCreateConstraint(ctx *middleware.Context, handler CreateConstraintHandler) *CreateConstraint {
	_ = "STUB: not implemented"
	return nil
}

/*
	CreateConstraint swagger:route POST /flags/{flagID}/segments/{segmentID}/constraints constraint createConstraint

CreateConstraint create constraint API
*/
type CreateConstraint struct {
	Context *middleware.Context
	Handler CreateConstraintHandler
}

func (o *CreateConstraint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
