// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// CreateConstraintOKCode is the HTTP code returned for type CreateConstraintOK
const CreateConstraintOKCode int = 200

/*
CreateConstraintOK the constraint created

swagger:response createConstraintOK
*/
type CreateConstraintOK struct {

	/*
	  In: Body
	*/
	Payload *models.Constraint `json:"body,omitempty"`
}

// NewCreateConstraintOK creates CreateConstraintOK with default headers values
func NewCreateConstraintOK() *CreateConstraintOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the create constraint o k response
func (o *CreateConstraintOK) WithPayload(payload *models.Constraint) *CreateConstraintOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the create constraint o k response
func (o *CreateConstraintOK) SetPayload(payload *models.Constraint) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *CreateConstraintOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
CreateConstraintDefault generic error response

swagger:response createConstraintDefault
*/
type CreateConstraintDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateConstraintDefault creates CreateConstraintDefault with default headers values
func NewCreateConstraintDefault(code int) *CreateConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the create constraint default response
func (o *CreateConstraintDefault) WithStatusCode(code int) *CreateConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the create constraint default response
func (o *CreateConstraintDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the create constraint default response
func (o *CreateConstraintDefault) WithPayload(payload *models.Error) *CreateConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the create constraint default response
func (o *CreateConstraintDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *CreateConstraintDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
