// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// DeleteConstraintOKCode is the HTTP code returned for type DeleteConstraintOK
const DeleteConstraintOKCode int = 200

/*
DeleteConstraintOK deleted

swagger:response deleteConstraintOK
*/
type DeleteConstraintOK struct {
}

// NewDeleteConstraintOK creates DeleteConstraintOK with default headers values
func NewDeleteConstraintOK() *DeleteConstraintOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *DeleteConstraintOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// Remove Content-Type on empty responses

/*
DeleteConstraintDefault generic error response

swagger:response deleteConstraintDefault
*/
type DeleteConstraintDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConstraintDefault creates DeleteConstraintDefault with default headers values
func NewDeleteConstraintDefault(code int) *DeleteConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the delete constraint default response
func (o *DeleteConstraintDefault) WithStatusCode(code int) *DeleteConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the delete constraint default response
func (o *DeleteConstraintDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the delete constraint default response
func (o *DeleteConstraintDefault) WithPayload(payload *models.Error) *DeleteConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the delete constraint default response
func (o *DeleteConstraintDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *DeleteConstraintDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
