// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteConstraintParams creates a new DeleteConstraintParams object
//
// There are no default values defined in the spec.
func NewDeleteConstraintParams() DeleteConstraintParams {
	_ = "STUB: not implemented"
	return *new(DeleteConstraintParams)
}

// DeleteConstraintParams contains all the bound params for the delete constraint operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteConstraint
type DeleteConstraintParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*numeric ID of the constraint
	  Required: true
	  Minimum: 1
	  In: path
	*/
	ConstraintID int64

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the segment
	  Required: true
	  Minimum: 1
	  In: path
	*/
	SegmentID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteConstraintParams() beforehand.
func (o *DeleteConstraintParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindConstraintID binds and validates parameter ConstraintID from path.
func (o *DeleteConstraintParams) bindConstraintID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateConstraintID carries out validations for parameter ConstraintID
func (o *DeleteConstraintParams) validateConstraintID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindFlagID binds and validates parameter FlagID from path.
func (o *DeleteConstraintParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *DeleteConstraintParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindSegmentID binds and validates parameter SegmentID from path.
func (o *DeleteConstraintParams) bindSegmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateSegmentID carries out validations for parameter SegmentID
func (o *DeleteConstraintParams) validateSegmentID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
