// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConstraintHandlerFunc turns a function with the right signature into a delete constraint handler
type DeleteConstraintHandlerFunc func(DeleteConstraintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConstraintHandlerFunc) Handle(params DeleteConstraintParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteConstraintHandler interface for that can handle valid delete constraint params
	return *new(middleware.Responder)
}

type DeleteConstraintHandler interface {
	Handle(DeleteConstraintParams) middleware.Responder
}

// NewDeleteConstraint creates a new http.Handler for the delete constraint operation
func NewDeleteConstraint(ctx *middleware.Context, handler DeleteConstraintHandler) *DeleteConstraint {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteConstraint swagger:route DELETE /flags/{flagID}/segments/{segmentID}/constraints/{constraintID} constraint deleteConstraint

DeleteConstraint delete constraint API
*/
type DeleteConstraint struct {
	Context *middleware.Context
	Handler DeleteConstraintHandler
}

func (o *DeleteConstraint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
