// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// FindConstraintsOKCode is the HTTP code returned for type FindConstraintsOK
const FindConstraintsOKCode int = 200

/*
FindConstraintsOK constraints under the segment

swagger:response findConstraintsOK
*/
type FindConstraintsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Constraint `json:"body,omitempty"`
}

// NewFindConstraintsOK creates FindConstraintsOK with default headers values
func NewFindConstraintsOK() *FindConstraintsOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the find constraints o k response
func (o *FindConstraintsOK) WithPayload(payload []*models.Constraint) *FindConstraintsOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find constraints o k response
func (o *FindConstraintsOK) SetPayload(payload []*models.Constraint) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *FindConstraintsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// return empty array

// let the recovery middleware deal with this

/*
FindConstraintsDefault generic error response

swagger:response findConstraintsDefault
*/
type FindConstraintsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindConstraintsDefault creates FindConstraintsDefault with default headers values
func NewFindConstraintsDefault(code int) *FindConstraintsDefault {
	_ = "STUB: not implemented"
	return nil
}

// WithStatusCode adds the status to the find constraints default response
func (o *FindConstraintsDefault) WithStatusCode(code int) *FindConstraintsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the find constraints default response
func (o *FindConstraintsDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the find constraints default response
func (o *FindConstraintsDefault) WithPayload(payload *models.Error) *FindConstraintsDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the find constraints default response
func (o *FindConstraintsDefault) SetPayload(payload *models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *FindConstraintsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
