// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindConstraintsHandlerFunc turns a function with the right signature into a find constraints handler
type FindConstraintsHandlerFunc func(FindConstraintsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindConstraintsHandlerFunc) Handle(params FindConstraintsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// FindConstraintsHandler interface for that can handle valid find constraints params
	return *new(middleware.Responder)
}

type FindConstraintsHandler interface {
	Handle(FindConstraintsParams) middleware.Responder
}

// NewFindConstraints creates a new http.Handler for the find constraints operation
func NewFindConstraints(ctx *middleware.Context, handler FindConstraintsHandler) *FindConstraints {
	_ = "STUB: not implemented"
	return nil
}

/*
	FindConstraints swagger:route GET /flags/{flagID}/segments/{segmentID}/constraints constraint findConstraints

FindConstraints find constraints API
*/
type FindConstraints struct {
	Context *middleware.Context
	Handler FindConstraintsHandler
}

func (o *FindConstraints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
