// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// NewPutConstraintParams creates a new PutConstraintParams object
//
// There are no default values defined in the spec.
func NewPutConstraintParams() PutConstraintParams {
	_ = "STUB: not implemented"
	return *new(PutConstraintParams)
}

// PutConstraintParams contains all the bound params for the put constraint operation
// typically these are obtained from a http.Request
//
// swagger:parameters putConstraint
type PutConstraintParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*create a constraint
	  Required: true
	  In: body
	*/
	Body *models.CreateConstraintRequest

	/*numeric ID of the constraint
	  Required: true
	  Minimum: 1
	  In: path
	*/
	ConstraintID int64

	/*numeric ID of the flag
	  Required: true
	  Minimum: 1
	  In: path
	*/
	FlagID int64

	/*numeric ID of the segment
	  Required: true
	  Minimum: 1
	  In: path
	*/
	SegmentID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutConstraintParams() beforehand.
func (o *PutConstraintParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object

// bindConstraintID binds and validates parameter ConstraintID from path.
func (o *PutConstraintParams) bindConstraintID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateConstraintID carries out validations for parameter ConstraintID
func (o *PutConstraintParams) validateConstraintID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindFlagID binds and validates parameter FlagID from path.
func (o *PutConstraintParams) bindFlagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateFlagID carries out validations for parameter FlagID
func (o *PutConstraintParams) validateFlagID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// bindSegmentID binds and validates parameter SegmentID from path.
func (o *PutConstraintParams) bindSegmentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// Parameter is provided by construction from the route

// validateSegmentID carries out validations for parameter SegmentID
func (o *PutConstraintParams) validateSegmentID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
