// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// PutConstraintOKCode is the HTTP code returned for type PutConstraintOK
const PutConstraintOKCode int = 200

/*
PutConstraintOK constraint just updated

swagger:response putConstraintOK
*/
type PutConstraintOK struct {

	/*
	  In: Body
	*/
	Payload *models.Constraint `json:"body,omitempty"`
}

// NewPutConstraintOK creates PutConstraintOK with default headers values
func NewPutConstraintOK() *PutConstraintOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the put constraint o k response
func (o *PutConstraintOK) WithPayload(payload *models.Constraint) *PutConstraintOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put constraint o k response
func (o *PutConstraintOK) SetPayload(payload *models.Constraint) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutConstraintOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
PutConstraintDefault generic error response

swagger:response putConstraintDefault
*/
type PutConstraintDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutConstraintDefault creates PutConstraintDefault with default headers values
func NewPutConstraintDefault(code int) *PutConstraintDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the put constraint default response
func (o *PutConstraintDefault) WithStatusCode(code int) *PutConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the put constraint default response
func (o *PutConstraintDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the put constraint default response
func (o *PutConstraintDefault) WithPayload(payload *models.Error) *PutConstraintDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the put constraint default response
func (o *PutConstraintDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PutConstraintDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
