// Code generated by go-swagger; DO NOT EDIT.

package constraint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutConstraintHandlerFunc turns a function with the right signature into a put constraint handler
type PutConstraintHandlerFunc func(PutConstraintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutConstraintHandlerFunc) Handle(params PutConstraintParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutConstraintHandler interface for that can handle valid put constraint params
	return *new(middleware.Responder)
}

type PutConstraintHandler interface {
	Handle(PutConstraintParams) middleware.Responder
}

// NewPutConstraint creates a new http.Handler for the put constraint operation
func NewPutConstraint(ctx *middleware.Context, handler PutConstraintHandler) *PutConstraint {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutConstraint swagger:route PUT /flags/{flagID}/segments/{segmentID}/constraints/{constraintID} constraint putConstraint

PutConstraint put constraint API
*/
type PutConstraint struct {
	Context *middleware.Context
	Handler PutConstraintHandler
}

func (o *PutConstraint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
