// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/url"
)

// GetHealthURL generates an URL for the get health operation
type GetHealthURL struct {
	_basePath string
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetHealthURL) WithBasePath(bp string) *GetHealthURL { _ = "STUB: not implemented"; return nil }

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetHealthURL) SetBasePath(bp string) {
	_ = "STUB: not implemented"

	// Build a url path and query string
	return
}

func (o *GetHealthURL) Build() (*url.URL, error) { _ = "STUB: not implemented"; return nil, nil }

// Must is a helper function to panic when the url builder returns an error
func (o *GetHealthURL) Must(u *url.URL, err error) *url.URL { _ = "STUB: not implemented"; return nil }

// String returns the string representation of the path with query string
func (o *GetHealthURL) String() string { _ = "STUB: not implemented"; return "" }

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetHealthURL) BuildFull(scheme, host string) (*url.URL, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StringFull returns the string representation of a complete url
func (o *GetHealthURL) StringFull(scheme, host string) string { _ = "STUB: not implemented"; return "" }
