// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openflagr/flagr/swagger_gen/models"
)

// GetHealthOKCode is the HTTP code returned for type GetHealthOK
const GetHealthOKCode int = 200

/*
GetHealthOK status of health check

swagger:response getHealthOK
*/
type GetHealthOK struct {

	/*
	  In: Body
	*/
	Payload *models.Health `json:"body,omitempty"`
}

// NewGetHealthOK creates GetHealthOK with default headers values
func NewGetHealthOK() *GetHealthOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the get health o k response
func (o *GetHealthOK) WithPayload(payload *models.Health) *GetHealthOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get health o k response
func (o *GetHealthOK) SetPayload(payload *models.Health) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *GetHealthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

/*
GetHealthDefault generic error response

swagger:response getHealthDefault
*/
type GetHealthDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHealthDefault creates GetHealthDefault with default headers values
func NewGetHealthDefault(code int) *GetHealthDefault { _ = "STUB: not implemented"; return nil }

// WithStatusCode adds the status to the get health default response
func (o *GetHealthDefault) WithStatusCode(code int) *GetHealthDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetStatusCode sets the status to the get health default response
func (o *GetHealthDefault) SetStatusCode(code int) { _ = "STUB: not implemented"; return }

// WithPayload adds the payload to the get health default response
func (o *GetHealthDefault) WithPayload(payload *models.Error) *GetHealthDefault {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get health default response
func (o *GetHealthDefault) SetPayload(payload *models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *GetHealthDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
